absl-py==1.4.0
appdirs==1.4.4
avalanche-lib==0.3.1
beautifulsoup4==4.12.2
cachetools==5.3.1
certifi==2023.5.7
charset-normalizer==3.1.0
click==8.1.3
contourpy==1.1.0
cycler==0.11.0
dill==0.3.6
docker-pycreds==0.4.0
filelock==3.12.2
fonttools==4.40.0
fsspec==2023.6.0
gdown==4.7.1
gitdb==4.0.10
GitPython==3.1.31
google-auth==2.21.0
google-auth-oauthlib==1.0.0
GPUtil==1.4.0
grpcio==1.56.0
huggingface-hub==0.15.1
idna==3.4
importlib-metadata==6.7.0
importlib-resources==5.12.0
joblib==1.2.0
kiwisolver==1.4.4
Markdown==3.4.3
MarkupSafe==2.1.3
matplotlib==3.7.1
numpy==1.24.4
oauthlib==3.2.2
packaging==23.1
pathtools==0.1.2
Pillow==9.5.0
protobuf==4.23.3
psutil==5.9.5
pyasn1==0.5.0
pyasn1-modules==0.3.0
pyparsing==3.1.0
PySocks==1.7.1
python-dateutil==2.8.2
pytorchcv==0.0.67
PyYAML==6.0
quadprog==0.1.11
requests==2.31.0
requests-oauthlib==1.3.1
rsa==4.9
safetensors==0.3.1
scikit-learn==1.2.2
scipy==1.10.1
sentry-sdk==1.26.0
setproctitle==1.3.2
six==1.16.0
smmap==5.0.0
soupsieve==2.4.1
tensorboard==2.13.0
tensorboard-data-server==0.7.1
threadpoolctl==3.1.0
timm==0.9.2
--extra-index-url https://download.pytorch.org/whl/cu113
torch==1.12.0+cu113 
--extra-index-url https://download.pytorch.org/whl/cu113
torchaudio==0.12.0+cu113 
torchmetrics==0.11.4 
--extra-index-url https://download.pytorch.org/whl/cu113
torchvision==0.13.0+cu113 
tqdm==4.65.0
typing_extensions==4.6.3
urllib3==1.26.16
wandb==0.15.4
Werkzeug==2.3.6
zipp==3.15.0
